### ISSUE TITLE
spin component y in .spn output might be wrong

### ISSUE THREAD

**Issue by lyglst** [Chengcheng-Xiao/VASP2WAN90_v2_fix#10]
in the .patch file line 1446 we have:
+                    CALL ECCP_NL_SPN(LMDIM,LMMAXC,CMPLX(0._q,1._q,q),CQIJ(1,1,NI,1+1+2*1),W2%CPROJ(NPRO_+1),W1%CPROJ(NPRO+1),CNLy)

Should that be:
+                    CALL ECCP_NL_SPN(LMDIM,LMMAXC,CMPLX(0._q,1._q,q),CQIJ(1,1,NI,1+1+2*0),W2%CPROJ(NPRO_+1),W1%CPROJ(NPRO+1),CNLy)

Just to be consistent with the Pauli matricies.

**Comment by Chengcheng-Xiao** [comment]
Yes, you are right! Good riddance for finding this typo, I'll fix this in a minute!

**Comment by Chengcheng-Xiao** [comment]
Fixed in 6496bd32f0607daf86dae2d51566d80b84944e12.
