### ISSUE TITLE
Direction of magnetization

### ISSUE THREAD

**Issue by WuzhangFang** [Chengcheng-Xiao/VASP2WAN90_v2_fix#16]
Hi Chengcheng,

Thanks for the nice codes. I have a question regarding the direction of magnetization. In your example04 or the example18 from wannier90 tutorial, the magnetization is set to parallel to the minus z direction then the calculated AHC is positive. If we reverse the magnetization, the AHC will become negative. I want to study some other materials. Except for symmetry analysis, is there a better way to study the dependence of magnetization on AHC rather than reconstructing the wannierisation from scratch?

Thanks,
Wuzhang Fang

**Comment by Chengcheng-Xiao** [comment]
I'd imagine one needs to do either symmetry analysis or full wannierization for that. But I'm not an expert on the subject, so take that with a grain of salt😉

**Comment by WuzhangFang** [comment]
Thanks!
