### ISSUE TITLE
Error while recompling the vasp after adding the patch in vasp.5.4.4pl2

### ISSUE THREAD

**Issue by hcut** [Chengcheng-Xiao/VASP2WAN90_v2_fix#24]
Hi,

I am getting the following error after following the instructions as suggested by you. Pl help

         make[2]: Entering directory '/home/simulations/vasp.5.4.4.pl2/build/std'
         mpif90 -ffree-form -ffree-line-length-none -w -O2 -I/usr/include -c wave_high.f90
         wave_high.f90:1510:36:

         1510 |     CALL  M_sum_d(W%WDES1%COMM_INB, WFMAG, 1)
         |                                    1
         ......
        1580 |     CALL  M_sum_d(W1%WDES1%COMM_INB, CWFMAG, 2)
         |                                     2
       Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/COMPLEX(8)).
       wave_high.f90:1408:36:

      1408 |     CALL  M_sum_d(W%WDES1%COMM_INB, WFMAG, 1)
      |                                    1
      ......
      1580 |     CALL  M_sum_d(W1%WDES1%COMM_INB, CWFMAG, 2)
      |                                     2
      Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/COMPLEX(8)).
      wave_high.f90:844:43:

      832 |             &           2* WA%WDES1%NRPLWV, W1%CPTWFP(1) , 1 , 0._q,  CTMP(1), 1)
      |                                            2
      ......
      844 |                &           WA%WDES1%NPROD, CRESUL , 1 , 1._q,  CTMP(1), 1)
      |                                           1
      Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
      wave_high.f90:847:43:

      847 |                &           WA%WDES1%NPROD, CRESUL , 1 , (1._q,0._q),  CTMP(1), 1)
      |                                           1
      ......
     1262 |          &              W%WDES%NRPLWV, W1%CPTWFP(1) , 1 , (0._q,0._q) ,  CPRO(1), 1)
      |                                       2    
     Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
     wave_high.f90:852:37:

     852 |     CALL  M_sum_z(WA%WDES1%COMM_INB, CTMP, SIZE(WA%CPTWFP,2))
      |                                     1
     ......
     1638 |     CALL  M_sum_z(W1%WDES1%COMM_INB, CSCPD, 1)
      |                                     2
     Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
     wave_high.f90:530:32:

     530 |     CALL DAXPY( W1%WDES1%NPL*2, SCALE, W1%CPTWFP(1), 1, W2%CPTWFP(1), 1)
       |                                1
     ......
     1642 |        CALL DAXPY(W1%WDES1%NPRO,-CSCPD,W2%CPROJ(1),1,W1%CPROJ(1),1)
      |                                2
     Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/COMPLEX(8)).
    wave_high.f90:533:34:

     533 |        CALL DAXPY( W1%WDES1%NPRO, SCALE, W1%CPROJ(1), 1,  W2%CPROJ(1), 1)
      |                                  1
     ......
     1642 |        CALL DAXPY(W1%WDES1%NPRO,-CSCPD,W2%CPROJ(1),1,W1%CPROJ(1),1)
       |                                2  
     Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/COMPLEX(8)).
     wave_high.f90:535:36:

      535 |        CALL DAXPY( W1%WDES1%NPRO*2, SCALE, W1%CPROJ(1),  1, W2%CPROJ(1), 1)
       |                                    1
    ......
    1642 |        CALL DAXPY(W1%WDES1%NPRO,-CSCPD,W2%CPROJ(1),1,W1%CPROJ(1),1)
      |                                2    
    Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/COMPLEX(8)).  
      wave_high.f90:545:61:

     545 |        CALL DAXPY( W1%WDES1%GRID%MPLWV*W1%WDES1%NRSPINORS*2, SCALE, W1%CR(1), 1,           W2%CR(1), 1)
      |                                                             1
      ......
     1642 |        CALL DAXPY(W1%WDES1%NPRO,-CSCPD,W2%CPROJ(1),1,W1%CPROJ(1),1)
      |                                2                             
     Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/COMPLEX(8)).
     wave_high.f90:3169:33:

      2322 |              CALL ZCOPY( WDESAUX%GRID%MPLWV*WDESAUX%NRSPINORS, WAUX%CR(1), 1,     WF(N_INTO_TOT-NB1+1,IK)%CR(1), 1)
      |                                                               2
      ......
       3169 |     CALL ZCOPY( W1%WDES1%NRPLWV, C, 1, W1%CPTWFP(1), 1)
      |                                 1
      Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
      wave_high.f90:3196:50:

       2322 |              CALL ZCOPY( WDESAUX%GRID%MPLWV*WDESAUX%NRSPINORS, WAUX%CR(1), 1,         WF(N_INTO_TOT-NB1+1,IK)%CR(1), 1)
      |                                                                              2
          ......
       3196 |     CALL ZCOPY( W1%WDES1%NRPLWV, W1%CPTWFP(1), 1, C, 1)
       |                                                  1
      Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
        make[2]: *** [makefile:169: wave_high.o] Error 1 
        make[2]: Leaving directory '/home/simulations/vasp.5.4.4.pl2/build/std'
         cp: cannot stat 'vasp': No such file or directory 
        make[1]: *** [makefile:142: all] Error 1 
        make[1]: Leaving directory '/home/simulations/vasp.5.4.4.pl2/build/std'
         make: *** [makefile:10: std] Error 2

**Comment by Chengcheng-Xiao** [comment]
Can you confirm that without the patch your toolchain (fortran compiler, math libs, etc...) works?

In the meantime, gfortran compiler flag `-fallow-argument-mismatch` might help.

**Comment by Chengcheng-Xiao** [comment]
Closed due to inactivity.
