### ISSUE TITLE
Can this be used for VASP2WAN90_v3?

### ISSUE THREAD

**Issue by hongyi-zhao** [Chengcheng-Xiao/VASP2WAN90_v2_fix#4]
Hi,

The wannier90 has released v3 version, can this also be used for VASP2WAN90_v3?

Regards

**Comment by NitroAshi** [comment]
I think you could use vasp2wan90v2 to generate files for wannier90, such as, wannier90.amn and wannier90.eig.
Then, you clould run wannier90_v3.x with those files.
It works fine for me

**Comment by hongyi-zhao** [comment]
@NitroAshi Do you also use this fixed patch or directly use the raw files shipped with vasp for compiliing with -DVASP2WANNIER90v2?

**Comment by Chengcheng-Xiao** [comment]
This patch does not support `LWANNIER90_RUN`. 
It can (as of now) only be used with VASP v5.4.4.
You can apply this patch and then compile VASP with any version of the libwannier code. 
Like @NitroAshi said, you can generate`.mmn`,`.amn`,`.nnkp` and `.eig` files with `LWANNIER90=.True.` and then run the `wannier90.x` program separately.

The goal of this patch is to enhance the compatibility between VASP and wannier90 (making it work and adding more abilities), I've now added the ability to control spinor projections (spinor channel and quantization axis), if you want to use(test) this, check out [this branch](https://github.com/Chengcheng-Xiao/VASP2WAN90_v2_fix/tree/spin_quantization_axis).

**Comment by NitroAshi** [comment]
> @NitroAshi Do you also use this fixed patch or directly use the raw files shipped with vasp for compiliing with -DVASP2WANNIER90v2?

I use this patch with _-DVASP2WANNIER90v2_  precompile flag.
