### ISSUE TITLE
.spn file? 

### ISSUE THREAD

**Issue by Chengcheng-Xiao** [Chengcheng-Xiao/VASP2WAN90_v2_fix#5]
The `spn` file contains:
- `<\psi_m| S | \psi_n>`, where S is the Pauli matrix, the pseudo part.
- `<\psi_m| \sigma_{ij} q_{ij} |\beta_i> <\beta_j| |\psi_n>`, the augmentation part.

The pseudo part can be easily obtained. For the augmentation part, refer to [pw2wannier90.f90](https://github.com/wannier-developers/wannier90/blob/develop/pwscf/v6.5/pw2wannier90.f90) (line 2469)
and VASP's `PEAD_CALC_OVERLAP` and `CALC_OVERLAP_GN`.

**Comment by Chengcheng-Xiao** [comment]
Done in 892432cea7af6c56c3b5ed74bff12f74c1b855e3, more tests needed. 

Does not work in parallel, because in parallel, bands are distributed. Need to figure out a way to sum them together. 

For now, use:
```
mpirun -np 1 vasp_ncl
```
with `ALGO=None`+`NELM=1` to skip everything alltogether.

For future:
`W1_GATHER` in `wave_high.F` doesn't work because it generates `wavefun1` instead of `wavefuna`.  Need to take a look at `PEAD_CALC_OVERLAP` routine in `pead.F`

**Comment by Chengcheng-Xiao** [comment]
Correctness checked. 

I'll leave the MPI support for the future, close for now.

**Comment by kibgboomba** [comment]
Thanks for your excellent code! I have a question. Will "ALGO=None NELM=1" affect the accuracy of the spn?

**Comment by Chengcheng-Xiao** [comment]
@kibgboomba  Thanks for reaching out. I've tested `ALGO=None` on several cases and did not see any accuracy impacts. If you have doubt, run a simple test shouldn't hurt🤔.

**Comment by kibgboomba** [comment]
> @kibgboomba Thanks for reaching out. I've tested `ALGO=None` on several cases and did not see any accuracy impacts. If you have doubt, run a simple test shouldn't hurt🤔.

Thank you very much!

**Comment by kibgboomba** [comment]
I have another question. Is the spn file need to be symmetrized like wannier90_hr.dat?

**Comment by Chengcheng-Xiao** [comment]
@kibgboomba  Re-symmetrization is always optional even for the hamiltonian, you should decide yourself🤓
